import { backspace } from "./actions/backspace";
import { c } from "./actions/c";
import { down } from "./actions/down";
import { end } from "./actions/end";
import { esc } from "./actions/esc";
import { h } from "./actions/h";
import { home } from "./actions/home";
import { l } from "./actions/l";
import { left } from "./actions/left";
import { m } from "./actions/m";
import { p } from "./actions/p";
import { right } from "./actions/right";
import { space } from "./actions/space";
import { up } from "./actions/up";
import { w } from "./actions/w";

export var actions = {};

backspace(actions);
c(actions);
down(actions);
end(actions);
esc(actions);
h(actions);
home(actions);
l(actions);
left(actions);
m(actions);
p(actions);
right(actions);
space(actions);
up(actions);
w(actions);