/// <reference path="_interfaces.ts" />
/// <reference path="_paramsInterfaces.ts" />
/// <reference path="inputs/_interfaces.ts" />
/// <reference path="../common/devices/_interfaces.ts" />
/// <reference path="../_lib/jquery/jquery.d.ts" />
/// <reference path="../_lib/knockout/knockout.d.ts" />
/// <reference path="../_lib/purl/purl.d.ts" />
/// <reference path="../_lib/pouch/pouch.d.ts" />
//@ sourceMappingURL=_references.js.map
